image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      npm install
      vsce package
vscode:
  extensions:
    - JesterOrNot.vscode-ion-shell@0.0.1:fcSDRJZ/Fmb9P9VY/RKvgg==
    - JesterOrNot.vscode-ion-shell@0.0.1:nA9AmqX9olWX7QWE1b3BOA==